//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseID { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<int> TrType { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ExpenseI_By { get; set; }
        public string Remarks { get; set; }
        public string Shift { get; set; }
        public string ExtraField { get; set; }
    }
}
